name: sync to pagure.io `s repositories
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**.txt"
      - "workflows/**.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to Pagure
        uses: yesolutions/mirror-action@master
        with:
          GIT_SSH_PRIVATE_KEY: ${{ secrets.PAGURE_RSA_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"
          REMOTE: ssh://git@pagure.io/rules.git
