name: A TO A:GH_PAGES
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 来源仓库
          source-repo: "git@github.com:china-fanxin/vuepress-blog.git"
          # 目标仓库
          destination-repo: "git@gitee.com:china-fanxin/vuepress-blog.git"
